"""Initial migration with new models

Revision ID: b4e91eb486a3
Revises: 
Create Date: 2025-11-17 14:00:38.879689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e91eb486a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('app_code', sa.String(length=255), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACT', 'INC', 'DEL', name='function_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_functions_id'), 'app_functions', ['id'], unique=False)
    op.create_table('app_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('app_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACT', 'INC', 'DEL', name='group_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_groups_id'), 'app_groups', ['id'], unique=False)
    op.create_table('app_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_permissions_id'), 'app_permissions', ['id'], unique=False)
    op.create_table('app_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('app_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACT', 'INC', 'DEL', name='role_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_roles_id'), 'app_roles', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_identifier'), 'otps', ['identifier'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('app_function_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['app_functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_function_permissions_id'), 'app_function_permissions', ['id'], unique=False)
    op.create_table('app_group_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['app_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['app_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_group_roles_group_id'), 'app_group_roles', ['group_id'], unique=False)
    op.create_index(op.f('ix_app_group_roles_id'), 'app_group_roles', ['id'], unique=False)
    op.create_index(op.f('ix_app_group_roles_role_id'), 'app_group_roles', ['role_id'], unique=False)
    op.create_table('app_role_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['app_functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['app_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_role_functions_function_id'), 'app_role_functions', ['function_id'], unique=False)
    op.create_index(op.f('ix_app_role_functions_id'), 'app_role_functions', ['id'], unique=False)
    op.create_index(op.f('ix_app_role_functions_role_id'), 'app_role_functions', ['role_id'], unique=False)
    op.create_table('app_user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ROLE', 'FUNCTION', 'GROUP', name='access_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_access_id'), 'app_user_access', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_access_user_id'), 'app_user_access', ['user_id'], unique=False)
    op.create_table('app_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['app_functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_permissions_function_id'), 'app_user_permissions', ['function_id'], unique=False)
    op.create_index(op.f('ix_app_user_permissions_id'), 'app_user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_permissions_user_id'), 'app_user_permissions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('user_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_app_id'), 'user_app', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_app_id'), table_name='user_app')
    op.drop_table('user_app')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_app_user_permissions_user_id'), table_name='app_user_permissions')
    op.drop_index(op.f('ix_app_user_permissions_id'), table_name='app_user_permissions')
    op.drop_index(op.f('ix_app_user_permissions_function_id'), table_name='app_user_permissions')
    op.drop_table('app_user_permissions')
    op.drop_index(op.f('ix_app_user_access_user_id'), table_name='app_user_access')
    op.drop_index(op.f('ix_app_user_access_id'), table_name='app_user_access')
    op.drop_table('app_user_access')
    op.drop_index(op.f('ix_app_role_functions_role_id'), table_name='app_role_functions')
    op.drop_index(op.f('ix_app_role_functions_id'), table_name='app_role_functions')
    op.drop_index(op.f('ix_app_role_functions_function_id'), table_name='app_role_functions')
    op.drop_table('app_role_functions')
    op.drop_index(op.f('ix_app_group_roles_role_id'), table_name='app_group_roles')
    op.drop_index(op.f('ix_app_group_roles_id'), table_name='app_group_roles')
    op.drop_index(op.f('ix_app_group_roles_group_id'), table_name='app_group_roles')
    op.drop_table('app_group_roles')
    op.drop_index(op.f('ix_app_function_permissions_id'), table_name='app_function_permissions')
    op.drop_table('app_function_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_identifier'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_app_roles_id'), table_name='app_roles')
    op.drop_table('app_roles')
    op.drop_index(op.f('ix_app_permissions_id'), table_name='app_permissions')
    op.drop_table('app_permissions')
    op.drop_index(op.f('ix_app_groups_id'), table_name='app_groups')
    op.drop_table('app_groups')
    op.drop_index(op.f('ix_app_functions_id'), table_name='app_functions')
    op.drop_table('app_functions')
    # ### end Alembic commands ###
